import next from "eslint-config-next/core-web-vitals";
import typescript from "eslint-config-next/typescript";

/* eslint-config-next ships a real flat config from v16, so it is spread
   directly. The FlatCompat shim this used to go through crashed on v16 —
   the plugin graph is self-referential, and the compat layer JSON-stringifies
   it to report errors. */
const config = [
  ...next,
  ...typescript,
  // Generated by Next on every build, and gitignored.
  { ignores: [".next/**", "node_modules/**", "scripts/**", "next-env.d.ts"] },
];

export default config;
